Completely rework EventT
ch3pjw/warp-test pull request #20
Opened 2017-11-20 14:49 UTC by ch3pjw

to allow for querying state and to allow for writing emitted events as we
go, rather than collecting them all up at the end. This makes failure
behaviour better/more intuitive.

2017-11-20 15:57 UTC, foolswood requested changes
Pretty much just that timeout from what I can grok.

2017-11-20 15:57 UTC, foolswood commented on src/Registration.hs
Erk!

2017-11-20 15:57 UTC, foolswood commented on src/Lib.hs
> +          -- FIXME: this now comes back with a result saying if you've
The idea being to come back and give a bit more feedback to the user here?

2017-11-20 16:17 UTC, ch3pjw commented on src/Registration.hs
Woops. Force pushed.

2017-11-20 16:17 UTC, ch3pjw commented on src/Lib.hs
> +          -- FIXME: this now comes back with a result saying if you've
Yeah, that's right. Didn't want to make a behaviour change here, so left it like it was for now.

2017-11-21 09:09 UTC, foolswood approved these changes

2017-11-21 09:09 UTC, merged